# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tanhua?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root  # 修改成你自己的

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
